"""Curated list of known data engineering/analytics terms for matching."""

from __future__ import annotations

from dataclasses import dataclass, field


@dataclass
class ReferenceTerm:
    """A known data domain term with optional Estonian translation hints."""

    en: str
    et_hints: list[str] = field(default_factory=list)
    category: str = ""


# Comprehensive list of data engineering, analytics, ML, and related terms.
# Each term has English canonical form, optional Estonian hints, and category.
REFERENCE_TERMS: list[ReferenceTerm] = [
    # ── Data Storage & Architecture ──
    ReferenceTerm("data warehouse", ["andmeladu", "andmeait"], "storage"),
    ReferenceTerm("data lake", ["andmejärv"], "storage"),
    ReferenceTerm("data lakehouse", ["andmejärvladu"], "storage"),
    ReferenceTerm("data mesh", ["andmevõrk", "andmevõrgustik"], "storage"),
    ReferenceTerm("data fabric", ["andmekude"], "storage"),
    ReferenceTerm("data mart", ["andmekiht", "teemaandmeladu"], "storage"),
    ReferenceTerm("data vault", ["andmehoidla"], "storage"),
    ReferenceTerm("data catalog", ["andmekataloog"], "storage"),
    ReferenceTerm("data store", ["andmehoidla"], "storage"),
    ReferenceTerm("database", ["andmebaas"], "storage"),
    ReferenceTerm("relational database", ["relatsiooniline andmebaas"], "storage"),
    ReferenceTerm("graph database", ["graafandmebaas"], "storage"),
    ReferenceTerm("time series database", ["aegridade andmebaas"], "storage"),
    ReferenceTerm("document database", ["dokumendiandmebaas"], "storage"),
    ReferenceTerm("key-value store", ["võtme-väärtuse hoidla"], "storage"),
    ReferenceTerm("column store", ["veeruhoidla", "veergpõhine andmebaas"], "storage"),
    ReferenceTerm("object storage", ["objektihoidla"], "storage"),
    ReferenceTerm("data repository", ["andmerepositorium"], "storage"),
    ReferenceTerm("metadata repository", ["metaandmete repositoorium"], "storage"),
    ReferenceTerm("data silo", ["andmesilod"], "storage"),

    # ── Data Modeling ──
    ReferenceTerm("data model", ["andmemudel"], "modeling"),
    ReferenceTerm("data modeling", ["andmete modelleerimine", "andmemudelite loomine"], "modeling"),
    ReferenceTerm("dimensional model", ["dimensioonimudel", "dimensiooniline mudel"], "modeling"),
    ReferenceTerm("star schema", ["täheskeem", "tähtskeemiga mudel"], "modeling"),
    ReferenceTerm("snowflake schema", ["lumehelvese skeem"], "modeling"),
    ReferenceTerm("fact table", ["fakttabel", "faktitabel"], "modeling"),
    ReferenceTerm("dimension table", ["dimensioonitabel"], "modeling"),
    ReferenceTerm("slowly changing dimension", ["aeglaselt muutuv dimensioon"], "modeling"),
    ReferenceTerm("surrogate key", ["surrogaatvõti", "asendvõti"], "modeling"),
    ReferenceTerm("natural key", ["naturaalne võti", "loomulik võti"], "modeling"),
    ReferenceTerm("primary key", ["primaarvõti", "esmane võti"], "modeling"),
    ReferenceTerm("foreign key", ["võõrvõti", "välisvõti"], "modeling"),
    ReferenceTerm("composite key", ["liitvõti"], "modeling"),
    ReferenceTerm("entity-relationship model", ["olem-seos mudel"], "modeling"),
    ReferenceTerm("normalization", ["normaliseerimine"], "modeling"),
    ReferenceTerm("denormalization", ["denormaliseerimine"], "modeling"),
    ReferenceTerm("schema", ["skeem"], "modeling"),
    ReferenceTerm("schema-on-read", ["lugemisskeem"], "modeling"),
    ReferenceTerm("schema-on-write", ["kirjutamisskeem"], "modeling"),
    ReferenceTerm("data dictionary", ["andmesõnastik"], "modeling"),
    ReferenceTerm("ontology", ["ontoloogia"], "modeling"),
    ReferenceTerm("taxonomy", ["taksonoomia"], "modeling"),
    ReferenceTerm("knowledge graph", ["teadmusgraaf"], "modeling"),

    # ── ETL / ELT / Data Integration ──
    ReferenceTerm("ETL", ["ETL"], "etl"),
    ReferenceTerm("ELT", ["ELT"], "etl"),
    ReferenceTerm("data pipeline", ["andmetorustik", "andmekonveier"], "etl"),
    ReferenceTerm("data ingestion", ["andmete sisestamine", "andmete vastuvõtt"], "etl"),
    ReferenceTerm("data extraction", ["andmete eraldamine"], "etl"),
    ReferenceTerm("data transformation", ["andmete teisendamine"], "etl"),
    ReferenceTerm("data loading", ["andmete laadimine"], "etl"),
    ReferenceTerm("change data capture", ["muudatusandmete hõive"], "etl"),
    ReferenceTerm("CDC", ["CDC"], "etl"),
    ReferenceTerm("batch processing", ["pakkimistöötlus", "pakktöötlus"], "etl"),
    ReferenceTerm("stream processing", ["vootöötlus", "voogtöötlus"], "etl"),
    ReferenceTerm("real-time processing", ["reaalajaline töötlus"], "etl"),
    ReferenceTerm("data integration", ["andmete integreerimine", "andmeintegratsioon"], "etl"),
    ReferenceTerm("data migration", ["andmete migreerimine", "andmemigratsioon"], "etl"),
    ReferenceTerm("data replication", ["andmete replikeerimine"], "etl"),
    ReferenceTerm("data synchronization", ["andmete sünkroniseerimine"], "etl"),
    ReferenceTerm("workflow orchestration", ["töövoo orkestratsioon"], "etl"),
    ReferenceTerm("data orchestration", ["andmete orkestratsioon"], "etl"),
    ReferenceTerm("idempotency", ["idempotentsus"], "etl"),
    ReferenceTerm("incremental load", ["inkrementaalne laadimine"], "etl"),
    ReferenceTerm("full load", ["täislaadimine"], "etl"),
    ReferenceTerm("data cleansing", ["andmete puhastamine", "andmepuhastus"], "etl"),
    ReferenceTerm("data wrangling", ["andmete korrastamine"], "etl"),
    ReferenceTerm("web scraping", ["veebikraapimine", "andmete kraapimine"], "etl"),

    # ── Analytics & BI ──
    ReferenceTerm("OLAP", ["OLAP"], "analytics"),
    ReferenceTerm("OLTP", ["OLTP"], "analytics"),
    ReferenceTerm("business intelligence", ["ärianalüütika", "äriteave"], "analytics"),
    ReferenceTerm("dashboard", ["armatuurlaud", "töölaud", "esipaneel"], "analytics"),
    ReferenceTerm("KPI", ["KPI", "tulemusnäitaja"], "analytics"),
    ReferenceTerm("ad-hoc query", ["ad hoc päring"], "analytics"),
    ReferenceTerm("report", ["aruanne", "raport"], "analytics"),
    ReferenceTerm("data visualization", ["andmete visualiseerimine", "andmevisualisatsioon"], "analytics"),
    ReferenceTerm("self-service analytics", ["iseteenindusanalüütika"], "analytics"),
    ReferenceTerm("drill-down", ["süvitsimine", "läbimine"], "analytics"),
    ReferenceTerm("slice and dice", ["lõikamine ja tükeldamine"], "analytics"),
    ReferenceTerm("pivot table", ["risttabel", "liigendtabel"], "analytics"),
    ReferenceTerm("metric", ["mõõdik", "mõõtarv"], "analytics"),
    ReferenceTerm("measure", ["mõõt", "mõõde"], "analytics"),
    ReferenceTerm("aggregation", ["agregatsioon", "koondamine"], "analytics"),
    ReferenceTerm("data analysis", ["andmeanalüüs"], "analytics"),
    ReferenceTerm("exploratory data analysis", ["uuriv andmeanalüüs"], "analytics"),
    ReferenceTerm("descriptive analytics", ["kirjeldav analüütika"], "analytics"),
    ReferenceTerm("predictive analytics", ["ennustav analüütika"], "analytics"),
    ReferenceTerm("prescriptive analytics", ["ettekirjutav analüütika"], "analytics"),
    ReferenceTerm("diagnostic analytics", ["diagnostiline analüütika"], "analytics"),
    ReferenceTerm("cohort analysis", ["kohordianalüüs"], "analytics"),
    ReferenceTerm("funnel analysis", ["lehtrianalüüs"], "analytics"),
    ReferenceTerm("sentiment analysis", ["sentimentanalüüs", "meelsusanalüüs"], "analytics"),
    ReferenceTerm("text analytics", ["tekstianalüütika"], "analytics"),

    # ── Data Governance & Quality ──
    ReferenceTerm("data governance", ["andmehaldus", "andmete juhtimine"], "governance"),
    ReferenceTerm("data quality", ["andmekvaliteet"], "governance"),
    ReferenceTerm("data lineage", ["andmete päritolu", "andmete pärinevus"], "governance"),
    ReferenceTerm("data steward", ["andmehaldur"], "governance"),
    ReferenceTerm("data owner", ["andmeomanik"], "governance"),
    ReferenceTerm("master data", ["põhiandmed", "masterandmed"], "governance"),
    ReferenceTerm("master data management", ["põhiandmete haldus"], "governance"),
    ReferenceTerm("metadata", ["metaandmed"], "governance"),
    ReferenceTerm("metadata management", ["metaandmete haldus"], "governance"),
    ReferenceTerm("data profiling", ["andmete profileerimine"], "governance"),
    ReferenceTerm("data audit", ["andmeaudit"], "governance"),
    ReferenceTerm("data compliance", ["andmete vastavus"], "governance"),
    ReferenceTerm("data privacy", ["andmekaitse", "privaatsus"], "governance"),
    ReferenceTerm("data security", ["andmeturve"], "governance"),
    ReferenceTerm("data retention", ["andmete säilitamine"], "governance"),
    ReferenceTerm("data anonymization", ["andmete anonümiseerimine"], "governance"),
    ReferenceTerm("data masking", ["andmete maskimine"], "governance"),
    ReferenceTerm("data classification", ["andmete klassifitseerimine"], "governance"),
    ReferenceTerm("data lifecycle", ["andmete elutsükkel"], "governance"),
    ReferenceTerm("GDPR", ["GDPR", "isikuandmete kaitse üldmäärus"], "governance"),
    ReferenceTerm("personally identifiable information", ["isikuandmed", "isikut tuvastav teave"], "governance"),
    ReferenceTerm("data breach", ["andmeleke"], "governance"),

    # ── Machine Learning ──
    ReferenceTerm("machine learning", ["masinõpe"], "ml"),
    ReferenceTerm("deep learning", ["süvaõpe"], "ml"),
    ReferenceTerm("neural network", ["närvivõrk", "neurovõrk"], "ml"),
    ReferenceTerm("artificial neural network", ["tehisnärvivõrk"], "ml"),
    ReferenceTerm("convolutional neural network", ["konvolutsiooniline närvivõrk"], "ml"),
    ReferenceTerm("recurrent neural network", ["rekurrentne närvivõrk"], "ml"),
    ReferenceTerm("supervised learning", ["juhendatud õpe"], "ml"),
    ReferenceTerm("unsupervised learning", ["juhendamata õpe"], "ml"),
    ReferenceTerm("semi-supervised learning", ["pooljuhendatud õpe"], "ml"),
    ReferenceTerm("reinforcement learning", ["stiimulõpe", "kinnitusõpe"], "ml"),
    ReferenceTerm("transfer learning", ["ülekandõpe", "siirdeõpe"], "ml"),
    ReferenceTerm("feature engineering", ["tunnuste loomine", "tunnuste konstrueerimine"], "ml"),
    ReferenceTerm("feature selection", ["tunnuste valik"], "ml"),
    ReferenceTerm("feature extraction", ["tunnuste eraldamine"], "ml"),
    ReferenceTerm("feature store", ["tunnuste hoidla"], "ml"),
    ReferenceTerm("training data", ["treenimisandmed", "õppimisandmed"], "ml"),
    ReferenceTerm("test data", ["testandmed"], "ml"),
    ReferenceTerm("validation data", ["valideerimisandmed"], "ml"),
    ReferenceTerm("overfitting", ["ülesobitamine", "üleõppimine"], "ml"),
    ReferenceTerm("underfitting", ["alasobitamine"], "ml"),
    ReferenceTerm("cross-validation", ["ristvalideerimine"], "ml"),
    ReferenceTerm("hyperparameter tuning", ["hüperparameetrite häälestamine"], "ml"),
    ReferenceTerm("gradient descent", ["gradientlaskumine"], "ml"),
    ReferenceTerm("backpropagation", ["tagasilevimine"], "ml"),
    ReferenceTerm("loss function", ["kaofunktsioon"], "ml"),
    ReferenceTerm("activation function", ["aktiveerimisfunktsioon"], "ml"),
    ReferenceTerm("regularization", ["regulariseerimine"], "ml"),
    ReferenceTerm("dropout", ["dropout", "väljajätmine"], "ml"),
    ReferenceTerm("batch normalization", ["partii normaliseerimine"], "ml"),
    ReferenceTerm("ensemble method", ["ansambelmeetod"], "ml"),
    ReferenceTerm("random forest", ["juhuslik mets"], "ml"),
    ReferenceTerm("decision tree", ["otsustuspuu"], "ml"),
    ReferenceTerm("gradient boosting", ["gradientvõimendamine"], "ml"),
    ReferenceTerm("support vector machine", ["tugivektor-masin", "tugivektormasin"], "ml"),
    ReferenceTerm("k-nearest neighbors", ["k-lähima naabri meetod"], "ml"),
    ReferenceTerm("naive Bayes", ["naiivne Bayes"], "ml"),
    ReferenceTerm("logistic regression", ["logistiline regressioon"], "ml"),
    ReferenceTerm("linear regression", ["lineaarne regressioon"], "ml"),
    ReferenceTerm("model training", ["mudeli treenimine"], "ml"),
    ReferenceTerm("model evaluation", ["mudeli hindamine"], "ml"),
    ReferenceTerm("model deployment", ["mudeli juurutamine"], "ml"),
    ReferenceTerm("model serving", ["mudeli teenindamine"], "ml"),
    ReferenceTerm("MLOps", ["MLOps"], "ml"),
    ReferenceTerm("AutoML", ["AutoML", "automaatne masinõpe"], "ml"),
    ReferenceTerm("explainability", ["seletatavus", "tõlgendatavus"], "ml"),
    ReferenceTerm("interpretability", ["tõlgendatavus"], "ml"),
    ReferenceTerm("bias", ["nihe", "kallutatus", "eelarvamus"], "ml"),
    ReferenceTerm("fairness", ["õiglus"], "ml"),
    ReferenceTerm("confusion matrix", ["segadus maatriks", "klassifikatsioonimaatriks"], "ml"),
    ReferenceTerm("precision", ["täpsus"], "ml"),
    ReferenceTerm("recall", ["saagis", "tundlikkus"], "ml"),
    ReferenceTerm("F1 score", ["F1-skoor"], "ml"),
    ReferenceTerm("ROC curve", ["ROC-kõver"], "ml"),
    ReferenceTerm("AUC", ["AUC"], "ml"),

    # ── NLP & AI ──
    ReferenceTerm("artificial intelligence", ["tehisintellekt"], "ai"),
    ReferenceTerm("natural language processing", ["loomuliku keele töötlus", "loomuliku keele töötlemine"], "ai"),
    ReferenceTerm("large language model", ["suur keelemudel"], "ai"),
    ReferenceTerm("transformer", ["transformer", "tähelepanumudel"], "ai"),
    ReferenceTerm("attention mechanism", ["tähelepanumehhanism"], "ai"),
    ReferenceTerm("tokenization", ["tokeniseerimine", "sõnestamine"], "ai"),
    ReferenceTerm("embedding", ["vektoresitus", "manustamine"], "ai"),
    ReferenceTerm("word embedding", ["sõnavektoresitus", "sõna manustamine"], "ai"),
    ReferenceTerm("generative AI", ["generatiivne tehisintellekt"], "ai"),
    ReferenceTerm("prompt engineering", ["viiba projekteerimine"], "ai"),
    ReferenceTerm("fine-tuning", ["peenhäälestamine", "peenhäälestus"], "ai"),
    ReferenceTerm("named entity recognition", ["nimeolemite tuvastamine"], "ai"),
    ReferenceTerm("text classification", ["teksti klassifitseerimine"], "ai"),
    ReferenceTerm("machine translation", ["masintõlge"], "ai"),
    ReferenceTerm("speech recognition", ["kõnetuvastus"], "ai"),
    ReferenceTerm("computer vision", ["arvutinägemine"], "ai"),
    ReferenceTerm("image recognition", ["pildituvastus", "kujutise tuvastamine"], "ai"),
    ReferenceTerm("object detection", ["objektituvastus"], "ai"),
    ReferenceTerm("generative adversarial network", ["generatiivne võistlusvõrk"], "ai"),
    ReferenceTerm("chatbot", ["vestlusrobot"], "ai"),
    ReferenceTerm("recommendation system", ["soovitussüsteem"], "ai"),
    ReferenceTerm("knowledge base", ["teadmusbaas"], "ai"),

    # ── Statistics ──
    ReferenceTerm("regression", ["regressioon"], "statistics"),
    ReferenceTerm("classification", ["klassifitseerimine", "klassifikatsioon"], "statistics"),
    ReferenceTerm("clustering", ["klasterdamine", "klasteranalüüs"], "statistics"),
    ReferenceTerm("dimensionality reduction", ["dimensionaalsuse vähendamine"], "statistics"),
    ReferenceTerm("principal component analysis", ["peakomponentanalüüs"], "statistics"),
    ReferenceTerm("time series", ["aegread", "aegrida"], "statistics"),
    ReferenceTerm("time series analysis", ["aegridade analüüs"], "statistics"),
    ReferenceTerm("forecasting", ["prognoosimine", "ennustamine"], "statistics"),
    ReferenceTerm("anomaly detection", ["anomaaliate tuvastamine"], "statistics"),
    ReferenceTerm("outlier detection", ["erindite tuvastamine"], "statistics"),
    ReferenceTerm("A/B testing", ["A/B testimine", "A/B test"], "statistics"),
    ReferenceTerm("hypothesis testing", ["hüpoteesi testimine"], "statistics"),
    ReferenceTerm("statistical significance", ["statistiline olulisus"], "statistics"),
    ReferenceTerm("p-value", ["p-väärtus"], "statistics"),
    ReferenceTerm("confidence interval", ["usaldusintervall"], "statistics"),
    ReferenceTerm("correlation", ["korrelatsioon"], "statistics"),
    ReferenceTerm("causation", ["põhjuslikkus"], "statistics"),
    ReferenceTerm("Bayesian inference", ["Bayesi järeldamine", "Bayesi statistika"], "statistics"),
    ReferenceTerm("Monte Carlo simulation", ["Monte Carlo simulatsioon"], "statistics"),
    ReferenceTerm("sampling", ["valimi moodustamine", "diskreetimist"], "statistics"),
    ReferenceTerm("probability distribution", ["tõenäosusjaotus"], "statistics"),
    ReferenceTerm("normal distribution", ["normaaljaotus"], "statistics"),
    ReferenceTerm("standard deviation", ["standardhälve"], "statistics"),
    ReferenceTerm("variance", ["dispersioon"], "statistics"),
    ReferenceTerm("mean", ["keskmine", "aritmeetiline keskmine"], "statistics"),
    ReferenceTerm("median", ["mediaan"], "statistics"),

    # ── Big Data & Distributed Systems ──
    ReferenceTerm("big data", ["suurandmed"], "bigdata"),
    ReferenceTerm("distributed computing", ["hajusarvutus"], "bigdata"),
    ReferenceTerm("distributed system", ["hajussüsteem"], "bigdata"),
    ReferenceTerm("MapReduce", ["MapReduce"], "bigdata"),
    ReferenceTerm("Apache Spark", ["Apache Spark"], "bigdata"),
    ReferenceTerm("Apache Hadoop", ["Apache Hadoop"], "bigdata"),
    ReferenceTerm("Apache Kafka", ["Apache Kafka"], "bigdata"),
    ReferenceTerm("Apache Flink", ["Apache Flink"], "bigdata"),
    ReferenceTerm("Apache Airflow", ["Apache Airflow"], "bigdata"),
    ReferenceTerm("message queue", ["sõnumijärjekord"], "bigdata"),
    ReferenceTerm("event streaming", ["sündmuste voogedastus"], "bigdata"),
    ReferenceTerm("event-driven architecture", ["sündmusepõhine arhitektuur"], "bigdata"),
    ReferenceTerm("data partitioning", ["andmete partitsioneerimine"], "bigdata"),
    ReferenceTerm("sharding", ["šardimine", "killustamine"], "bigdata"),
    ReferenceTerm("horizontal scaling", ["horisontaalne skaleerimine"], "bigdata"),
    ReferenceTerm("vertical scaling", ["vertikaalne skaleerimine"], "bigdata"),
    ReferenceTerm("load balancing", ["koormuse tasakaalustamine"], "bigdata"),
    ReferenceTerm("fault tolerance", ["tõrketaluvus"], "bigdata"),
    ReferenceTerm("high availability", ["kõrge käideldavus"], "bigdata"),
    ReferenceTerm("data locality", ["andmete lokaalsus"], "bigdata"),
    ReferenceTerm("in-memory computing", ["mälupõhine arvutus"], "bigdata"),
    ReferenceTerm("parallel processing", ["paralleeltöötlus"], "bigdata"),

    # ── Cloud & Infrastructure ──
    ReferenceTerm("cloud computing", ["pilvandmetöötlus", "pilvarvutus"], "cloud"),
    ReferenceTerm("data engineering", ["andmetehnika", "andmete inseneeria"], "cloud"),
    ReferenceTerm("infrastructure as code", ["infrastruktuur koodina"], "cloud"),
    ReferenceTerm("containerization", ["konteineriseerimine"], "cloud"),
    ReferenceTerm("microservices", ["mikroteenused"], "cloud"),
    ReferenceTerm("serverless", ["serverivaba"], "cloud"),
    ReferenceTerm("API", ["API", "rakendusliides"], "cloud"),
    ReferenceTerm("REST API", ["REST API", "REST-liides"], "cloud"),
    ReferenceTerm("CI/CD", ["CI/CD", "pidev integratsioon"], "cloud"),
    ReferenceTerm("DevOps", ["DevOps"], "cloud"),
    ReferenceTerm("DataOps", ["DataOps"], "cloud"),
    ReferenceTerm("version control", ["versioonihaldus"], "cloud"),
    ReferenceTerm("data versioning", ["andmete versioonihaldus"], "cloud"),

    # ── SQL & Query Languages ──
    ReferenceTerm("SQL", ["SQL"], "sql"),
    ReferenceTerm("NoSQL", ["NoSQL"], "sql"),
    ReferenceTerm("query optimization", ["päringu optimeerimine"], "sql"),
    ReferenceTerm("index", ["indeks"], "sql"),
    ReferenceTerm("join", ["ühend", "liitmine"], "sql"),
    ReferenceTerm("subquery", ["alampäring"], "sql"),
    ReferenceTerm("view", ["vaade"], "sql"),
    ReferenceTerm("materialized view", ["materialiseeritud vaade"], "sql"),
    ReferenceTerm("stored procedure", ["salvestatud protseduur"], "sql"),
    ReferenceTerm("trigger", ["päästik", "trigger"], "sql"),
    ReferenceTerm("transaction", ["transaktsioon"], "sql"),
    ReferenceTerm("ACID", ["ACID"], "sql"),
    ReferenceTerm("eventual consistency", ["lõplik konsistentsus"], "sql"),
    ReferenceTerm("CAP theorem", ["CAP-teoreem"], "sql"),
    ReferenceTerm("window function", ["aknafunktsioon"], "sql"),
    ReferenceTerm("common table expression", ["ühistabel-avaldis", "CTE"], "sql"),

    # ── Data Formats & Serialization ──
    ReferenceTerm("JSON", ["JSON"], "formats"),
    ReferenceTerm("CSV", ["CSV"], "formats"),
    ReferenceTerm("Parquet", ["Parquet"], "formats"),
    ReferenceTerm("Avro", ["Avro"], "formats"),
    ReferenceTerm("ORC", ["ORC"], "formats"),
    ReferenceTerm("XML", ["XML"], "formats"),
    ReferenceTerm("YAML", ["YAML"], "formats"),
    ReferenceTerm("data serialization", ["andmete serialiseerimine"], "formats"),
    ReferenceTerm("data format", ["andmevorming"], "formats"),
    ReferenceTerm("schema evolution", ["skeemi evolutsioon"], "formats"),
    ReferenceTerm("data compression", ["andmete tihendamine"], "formats"),

    # ── Data Science Process ──
    ReferenceTerm("data science", ["andmeteadus"], "process"),
    ReferenceTerm("data-driven", ["andmepõhine"], "process"),
    ReferenceTerm("data literacy", ["andmekirjaoskus", "andmepädevus"], "process"),
    ReferenceTerm("data democratization", ["andmete demokratiseerimine"], "process"),
    ReferenceTerm("data product", ["andmetoode"], "process"),
    ReferenceTerm("data contract", ["andmeleping"], "process"),
    ReferenceTerm("data observability", ["andmete jälgitavus"], "process"),
    ReferenceTerm("data reliability", ["andmete usaldusväärsus"], "process"),
    ReferenceTerm("data freshness", ["andmete värskus"], "process"),
    ReferenceTerm("data completeness", ["andmete täielikkus"], "process"),
    ReferenceTerm("data accuracy", ["andmete täpsus"], "process"),
    ReferenceTerm("data consistency", ["andmete kooskõlalisus", "andmete konsistentsus"], "process"),
    ReferenceTerm("reproducibility", ["reprodutseeritavus", "korratavus"], "process"),
    ReferenceTerm("experiment tracking", ["katse jälgimine"], "process"),

    # ── Semantic / Web / Open Data ──
    ReferenceTerm("open data", ["avaandmed"], "opendata"),
    ReferenceTerm("linked data", ["lingitud andmed", "seotud andmed"], "opendata"),
    ReferenceTerm("semantic web", ["semantiline veeb"], "opendata"),
    ReferenceTerm("RDF", ["RDF"], "opendata"),
    ReferenceTerm("SPARQL", ["SPARQL"], "opendata"),
    ReferenceTerm("data portal", ["andmeportaal"], "opendata"),
    ReferenceTerm("API endpoint", ["API lõpp-punkt"], "opendata"),
    ReferenceTerm("data sharing", ["andmete jagamine"], "opendata"),
    ReferenceTerm("interoperability", ["koostalitlusvõime"], "opendata"),
    ReferenceTerm("data standard", ["andmestandard"], "opendata"),

    # ── Security & Access ──
    ReferenceTerm("access control", ["juurdepääsukontroll"], "security"),
    ReferenceTerm("role-based access control", ["rollipõhine juurdepääsukontroll"], "security"),
    ReferenceTerm("encryption", ["krüpteerimine"], "security"),
    ReferenceTerm("authentication", ["autentimine", "tuvastamine"], "security"),
    ReferenceTerm("authorization", ["autoriseerimine", "volitamine"], "security"),
    ReferenceTerm("data encryption", ["andmete krüpteerimine"], "security"),
    ReferenceTerm("tokenization", ["tokeniseerimine"], "security"),
    ReferenceTerm("hashing", ["räsimine"], "security"),
    ReferenceTerm("cybersecurity", ["küberturvalisus"], "security"),

    # ── IoT & Edge ──
    ReferenceTerm("Internet of Things", ["asjade internet"], "iot"),
    ReferenceTerm("IoT", ["IoT", "asjade internet"], "iot"),
    ReferenceTerm("edge computing", ["servaarvutus", "äärearvutus"], "iot"),
    ReferenceTerm("sensor data", ["anduriandmed"], "iot"),
    ReferenceTerm("telemetry", ["telemeetria"], "iot"),
    ReferenceTerm("digital twin", ["digitaalne kaksik"], "iot"),

    # ── Misc Data Terms ──
    ReferenceTerm("dataset", ["andmestik", "andmehulk"], "misc"),
    ReferenceTerm("data point", ["andmepunkt"], "misc"),
    ReferenceTerm("record", ["kirje"], "misc"),
    ReferenceTerm("field", ["väli"], "misc"),
    ReferenceTerm("attribute", ["atribuut", "omadus"], "misc"),
    ReferenceTerm("variable", ["muutuja"], "misc"),
    ReferenceTerm("label", ["silt", "märgend"], "misc"),
    ReferenceTerm("annotation", ["annotatsioon", "märgendus"], "misc"),
    ReferenceTerm("ground truth", ["tõene väärtus", "põhitõde"], "misc"),
    ReferenceTerm("benchmark", ["võrdlusanalüüs", "võrdlustest"], "misc"),
    ReferenceTerm("baseline", ["baastase", "lähtetase"], "misc"),
    ReferenceTerm("latency", ["latentsus", "viivitus"], "misc"),
    ReferenceTerm("throughput", ["läbilaskevõime"], "misc"),
    ReferenceTerm("scalability", ["skaleeritavus", "mastaabitavus"], "misc"),
    ReferenceTerm("data drift", ["andmete triivimine"], "misc"),
    ReferenceTerm("concept drift", ["kontseptsiooni triivimine"], "misc"),
    ReferenceTerm("batch", ["pakk", "partii"], "misc"),
    ReferenceTerm("pipeline", ["torustik", "konveier"], "misc"),
    ReferenceTerm("workflow", ["töövoog"], "misc"),
    ReferenceTerm("DAG", ["DAG", "suunatud atsükliline graaf"], "misc"),
    ReferenceTerm("idempotent", ["idempotentne"], "misc"),
]


def get_all_terms() -> list[ReferenceTerm]:
    """Return the full list of reference terms."""
    return REFERENCE_TERMS


def get_en_terms_set() -> set[str]:
    """Return a set of all English terms (lowercased) for quick lookup."""
    return {t.en.lower() for t in REFERENCE_TERMS}


def get_et_hints_map() -> dict[str, str]:
    """Return a mapping of Estonian hint → English term (lowercased).

    Useful for matching Estonian abstracts back to the English canonical form.
    """
    mapping: dict[str, str] = {}
    for term in REFERENCE_TERMS:
        for hint in term.et_hints:
            mapping[hint.lower()] = term.en.lower()
    return mapping
